### ISSUE TITLE
Create and implement a set of error handling conventions.

### ISSUE THREAD

**Issue by SavannahEvans** [metasys-server/basic-services-dotnet#10]
Identify all possible errors for:
- [x] Login
- [x] Refresh
- [x] GetObjectIdentifier
- [x] ReadProperty
- [x] ReadPropertyMultiple

Options to communicate errors:
* Throw exceptions
* Return an error code and use output params
* Return a tuple with return type and error

**Comment by SavannahEvans** [comment]
Resource that explains how to use exceptions which create COM errors using HRESULTs: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/9ztbc5s1(v=vs.90)

**Comment by buldrinie** [comment]
The suggested approach is to use Exceptions to be sure that failures do not go unnoticed because calling code didn't check a return code.
Metasys requests is a critical point of failure of the SDK, so it is important to manage this kind of errors using a custom Exception that includes the specific HTTP Error and message returned by Metasys API. In addition, if there are others possible points of failure in the SDK logic, they need to be managed raising a specific exception of the Framework (if available) or a customized one.
See the link below as a reference for Exceptions Best Practice:
https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions

**Comment by buldrinie** [comment]
Another point of attention are the return values of the methods. While the information is not found or available, the preferred response type is a null, e.g.  Object Identifier not found, Attribute name not valid. In this way the SDK consumer can check the response in a reliable way, whilst having an empty object with default values can lead to undiscovered bugs, since the subsequent codes will not fail as a null reference Exception. The cases that now are handled with a default response object for every kind of error, e.g. GetObjectIdentifier, ReadProperty, need to figure out  the distinction between an HTTP error (exception) and when the information is not found (return null). In the case of ReadPropertyMultiple method we can have nulls on the Variants response collection when attribute requested is not valid for the specific object or the GUID is not found at all.

**Comment by buldrinie** [comment]
https://github.com/metasys-server/basic-services-dotnet/pull/36 Next step will be to have in our Custom Exception the HttpStatus Code as well. @SavannahEvans, I would also transform the Variant structure in a Class to allow null return. Right now I returned an empty object in the NotFound case, but null is preferred.

**Comment by SavannahEvans** [comment]
I created 6 different exceptions the program can throw. Please review and approve of these error messages. Currently the MetasysHttp exceptions just use the Flurl error messages - if these need to be customized it is an easy fix.

**Comment by buldrinie** [comment]
Ok for the six types of Exceptions and the error messages. For the MetasysHttpException I would leave the entire Flurl message as it is, since contains enough details to debug and is well structured. For further details the Developer can inspect the HttpCall object.

**Comment by mgwelch** [comment]
> I created 6 different exceptions the program can throw. Please review and approve of these error messages.

Where are they for review?

**Comment by SavannahEvans** [comment]
@mgwelch they are here: https://github.com/metasys-server/basic-services-dotnet/blob/master/MetasysServices/Exceptions/MetasysException.cs. Sorry for not including a link.

**Comment by buldrinie** [comment]
@SavannahEvans, I agree with @mgwelch to derive all our custom Exceptions from a base MetasysException Class. In this way consumers can catch all the Metasys exceptions in one place, if they wish.

**Comment by SavannahEvans** [comment]
I will implement one base MetasysException.

**Comment by SavannahEvans** [comment]
Addressed in #50.
