### ISSUE TITLE
Implement enum conversions for TraditionalClient

### ISSUE THREAD

**Issue by buldrinie** [metasys-server/basic-services-dotnet#31]
Create C# enum definition that matches the Metasys API definition, e.g Reliability, Priority

**Comment by buldrinie** [comment]
@SavannahEvans, @mgwelch, just inspected the Metasys API enumset for Reliability, but I think it's easier if we can get the server C# enum definition.  How about if the Metasys API enumSets are updated, can we assume to synchronize it on our SDK manually once and rarely in time or we need a dynamic object? for the Priority can't find a matching enumset.
![enum c#](https://user-images.githubusercontent.com/54939252/65951548-8d3aed80-e440-11e9-8a6b-80a51a9b0b87.JPG)
![enumset](https://user-images.githubusercontent.com/54939252/65951550-8d3aed80-e440-11e9-88f3-0a6782aac6d3.JPG)

**Comment by mgwelch** [comment]
>just inspected the Metasys API enumset for Reliability, but I think it's easier if we can get the server C# enum definition. How about if the Metasys API enumSets are updated, can we assume to synchronize it on our SDK manually once and rarely in time or we need a dynamic object? for the Priority can't find a matching enumset.

Some comments:

1. Creating a C# enum may be useful if the SDK is going to do a lot of processing of those values; however just for displaying reliability to a user/client we should rely on our resource files.
2. Enums currently only change on release boundaries. So it should be possible to keep in sync at the end of each release. Things like reliability don't change very often I guess and even if values were added its unlikely they are useful in the SDK.
3. Rather than C# enums it might be better to just get used to the constant strings defined by our enums. This would probably be preferred if you only need to know one or two values. I don't see it likely that the SDK would need to worry about more values. Perhaps you are thinking of exposing the C# Reliability enum for clients so that they can execute logic against it? 
4. There are several priority enum sets. And often times priority is modeled as an int (0-15) in the UI and other times as an enum. The one that is most often used is `writePriorityEnumSet`. That's the one that I believe always applies to attributes.

**Comment by buldrinie** [comment]
@SavannahEvans implementation seemed to suggest to create a strong typed Enum, but I agree with @mgwelch that we can treat enumSet as strings, since its main usage is for displaying. In this way we can just provide methods to get translations from .resx files.

**Comment by buldrinie** [comment]
Implemented with this commit https://github.com/metasys-server/basic-services-dotnet/commit/c6d4700f7a47141ad5117637c2c6986f88697a42 localization support using .resources files that @SavannahEvans generated. I modified the resources folder structure to match the satellite assemblies convention and set each file as embedded resource.
![embedded resources](https://user-images.githubusercontent.com/54939252/66491936-e09de300-eab3-11e9-809f-c7a29f44af25.JPG)


![convention of satellite assembly](https://user-images.githubusercontent.com/54939252/66491335-d9c2a080-eab2-11e9-87bf-6d5a61583329.JPG). 

I kept also the txt file, just in case we need to do modifications. We can create the .resources file from the .txt using ResGen command. The default namespace for the Resources is by convention JohnsonControls.Metasys.BasicServices.Resources as you can see from the ResourceManager initialization.  I added the Localize method to the MetasysClient. The function accepts an optional parameter to set the locale, otherwise Metasys Client Culture property will be used. The escalation logic for the translation lookup is: requested culture, en-US, and finally the resource key.
In this way we manage (without Exception) cases where resource localization is not available for a specific culture. @mgwelch, if this is compliant with your original idea we can close this issue for the first release. 

![localization](https://user-images.githubusercontent.com/54939252/66491755-93217600-eab3-11e9-8de8-cc2af4dfca8b.JPG)

**Comment by mgwelch** [comment]
> @mgwelch, if this is compliant with your original idea we can close this issue for the first release. 

This seems to meet the intent. My main concern was that customers could get their localized strings. And this seems to accomplish that.
